//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
//!
//! Index of the auto-generated entities. As more tables are added, the code
//! generator lists each one's module here.

pub mod prelude; // convenient re-exports (e.g. `Users`) for importing entities
pub mod users; // the `users` table definition
