//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
//!
//! A "prelude" gathers the most-used names so other files can import them in
//! one line. Here it renames the `users` entity to the friendlier `Users`.
pub use super::users::Entity as Users;
