//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
//!
//! NOTE: This file is auto-generated from the database schema. If you ever
//! re-run the code generator it will be overwritten — including the comments
//! below. The hand-written behavior (validation, lookups, …) lives in the
//! sibling file `../users.rs`, not here.
//!
//! This struct mirrors one row of the `users` table: each field is one column.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

// The `#[derive(...)]` line auto-implements common traits: cloning, debug
// printing, equality, JSON (de)serialization, and — via `DeriveEntityModel` —
// all the SeaORM plumbing that ties this struct to the `users` table.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone, // when the row was first inserted
    pub updated_at: DateTimeWithTimeZone, // when the row was last changed
    #[sea_orm(primary_key)]
    pub id: i32, // internal numeric primary key (never exposed publicly)
    pub pid: Uuid, // public id: a random UUID used in URLs/tokens instead of `id`
    #[sea_orm(unique)]
    pub email: String, // login email; `unique` = no two users can share it
    pub password: String, // the password *hash* (never the plain password)
    #[sea_orm(unique)]
    pub api_key: String, // token for API authentication; also unique
    pub name: String, // the user's display name

    // The fields below are `Option<...>`, meaning they can be empty (NULL in
    // the database). They hold short-lived tokens and timestamps used by the
    // password-reset, email-verification, and magic-link flows.
    pub reset_token: Option<String>, // current password-reset token, if any
    pub reset_sent_at: Option<DateTimeWithTimeZone>, // when that reset was requested
    pub email_verification_token: Option<String>, // token emailed to confirm address
    pub email_verification_sent_at: Option<DateTimeWithTimeZone>, // when it was sent
    pub email_verified_at: Option<DateTimeWithTimeZone>, // set once the email is confirmed
    pub magic_link_token: Option<String>, // current passwordless-login token, if any
    pub magic_link_expiration: Option<DateTimeWithTimeZone>, // when that link stops working
}

// Relations to other tables. There are none yet (the `users` table stands
// alone), so this enum is intentionally empty.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
